[tool.ruff]
select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "UP",
    "A",
    "B",
    "C4",
    "EM",
    "EXE",
    "INP",
    "PIE",
    "TCH",
    "NPY",
    "RUF",
    "PD003",
    "PD004",
    "PD007",
    "PD008",
    "PD009",
    "PD010",
    "PD012",
    "PD013",
    "PD015",
]
extend-exclude = ["src/solvers/legacy"]

target-version = "py310"

[tool.ruff.pep8-naming]
ignore-names = ["F"]
